//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Integrated_Query_App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language_Integrated_Query_App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;first_name&quot;: &quot;Ivan&quot;,
        ///    &quot;last_name&quot;: &quot;Petrov&quot;,
        ///    &quot;test_name&quot;: &quot;Maths&quot;,
        ///    &quot;mark&quot;: 5,
        ///    &quot;date_pass&quot;: &quot;2021-06-21T15:00:00&quot;
        ///  },
        ///  {
        ///    &quot;first_name&quot;: &quot;Peotor&quot;,
        ///    &quot;last_name&quot;: &quot;Sidorov&quot;,
        ///    &quot;test_name&quot;: &quot;PE&quot;,
        ///    &quot;mark&quot;: 4,
        ///    &quot;date_pass&quot;: &quot;2021-06-21T15:30:00&quot;
        ///  },
        ///  {
        ///    &quot;first_name&quot;: &quot;Andrey&quot;,
        ///    &quot;last_name&quot;: &quot;Vasilev&quot;,
        ///    &quot;test_name&quot;: &quot;Maths&quot;,
        ///    &quot;mark&quot;: 4,
        ///    &quot;date_pass&quot;: &quot;2021-06-21T12:20:00&quot;
        ///  },
        ///  {
        ///    &quot;first_name&quot;: &quot;Svetlana&quot;,
        ///    &quot;last_name&quot;: &quot;Petro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
    }
}
