//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace module_10.MockData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("module_10.MockData.MockResources", typeof(MockResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 1,
        ///    &quot;subject&quot;: &quot;Philosophy of ancient Rome&quot;,
        ///    &quot;lectureId&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: 2,
        ///    &quot;subject&quot;: &quot;Theory of Algorithms&quot;,
        ///    &quot;lectureId&quot;: 2
        ///  },
        ///  {
        ///    &quot;id&quot;: 3,
        ///    &quot;subject&quot;: &quot;Passive voice&quot;,
        ///    &quot;lectureId&quot;: 5
        ///  },
        ///  {
        ///    &quot;id&quot;: 4,
        ///    &quot;subject&quot;: &quot;Transistors in modern electronics&quot;,
        ///    &quot;lectureId&quot;: 7
        ///  },
        ///  {
        ///    &quot;id&quot;: 5,
        ///    &quot;subject&quot;: &quot;Mathematical modeling&quot;,
        ///    &quot;lectureId&quot;: 6
        ///  },
        ///  {
        ///    &quot;id&quot;: 6,
        ///    &quot;subject&quot;: &quot;What a philosophy is: subject, objec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string All_Homework_json {
            get {
                return ResourceManager.GetString("All_Homework.json", resourceCulture);
            }
        }
    }
}
