//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace module_10.MockData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("module_10.MockData.MockResources", typeof(MockResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 1,
        ///    &quot;subject&quot;: &quot;Philosophy of ancient Rome&quot;,
        ///    &quot;lectureId&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: 2,
        ///    &quot;subject&quot;: &quot;Theory of Algorithms&quot;,
        ///    &quot;lectureId&quot;: 2
        ///  },
        ///  {
        ///    &quot;id&quot;: 3,
        ///    &quot;subject&quot;: &quot;Passive voice&quot;,
        ///    &quot;lectureId&quot;: 5
        ///  },
        ///  {
        ///    &quot;id&quot;: 4,
        ///    &quot;subject&quot;: &quot;Transistors in modern electronics&quot;,
        ///    &quot;lectureId&quot;: 7
        ///  },
        ///  {
        ///    &quot;id&quot;: 5,
        ///    &quot;subject&quot;: &quot;Mathematical modeling&quot;,
        ///    &quot;lectureId&quot;: 6
        ///  },
        ///  {
        ///    &quot;id&quot;: 6,
        ///    &quot;subject&quot;: &quot;What a philosophy is: subject, objec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string All_Homework_json {
            get {
                return ResourceManager.GetString("All_Homework.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;studentId&quot;: 1,
        ///    &quot;homeworkId&quot;: 1
        ///  },
        ///  {
        ///    &quot;studentId&quot;: 2,
        ///    &quot;homeworkId&quot;: 1
        ///  },
        ///  {
        ///    &quot;studentId&quot;: 3,
        ///    &quot;homeworkId&quot;: 1
        ///  },
        ///  {
        ///    &quot;studentId&quot;: 4,
        ///    &quot;homeworkId&quot;: 1
        ///  },
        ///  {
        ///    &quot;studentId&quot;: 5,
        ///    &quot;homeworkId&quot;: 1
        ///  },
        ///  {
        ///    &quot;studentId&quot;: 1,
        ///    &quot;homeworkId&quot;: 2
        ///  },
        ///  {
        ///    &quot;studentId&quot;: 2,
        ///    &quot;homeworkId&quot;: 2
        ///  },
        ///  {
        ///    &quot;studentId&quot;: 3,
        ///    &quot;homeworkId&quot;: 2
        ///  },
        ///  {
        ///    &quot;studentId&quot;: 4,
        ///    &quot;homeworkId&quot;: 2
        ///  },
        ///  {
        ///    &quot;studentId&quot;: 5,
        ///    &quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string All_HomeworksStudents_json {
            get {
                return ResourceManager.GetString("All_HomeworksStudents.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 1,
        ///    &quot;name&quot;: &quot;Vitaly Genadievich Gromov&quot;,
        ///    &quot;email&quot;: &quot;vitaly.gromov@universitat.ru&quot;,
        ///    &quot;phone&quot;: &quot;+79010078912&quot;,
        ///    &quot;age&quot;: 45
        ///  },
        ///  {
        ///    &quot;id&quot;: 2,
        ///    &quot;name&quot;: &quot;Anatoly Vladimirovich Smolny&quot;,
        ///    &quot;email&quot;: &quot;anatoly.smolny@universitat.ru&quot;,
        ///    &quot;phone&quot;: &quot;+79011010015&quot;,
        ///    &quot;age&quot;: 52
        ///  },
        ///  {
        ///    &quot;id&quot;: 3,
        ///    &quot;name&quot;: &quot;Galina Petrovna Antonuk&quot;,
        ///    &quot;email&quot;: &quot;galina.antonuk@universitat.ru&quot;,
        ///    &quot;phone&quot;: &quot;+79019661234&quot;,
        ///    &quot;age&quot;: 43
        ///  },
        ///  {
        ///    &quot;id&quot;: 4,
        ///    &quot;name&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string All_Lectors_json {
            get {
                return ResourceManager.GetString("All_Lectors.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 1,
        ///    &quot;lectureName&quot;: &quot;Philosophy&quot;,
        ///    &quot;lectorId&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: 2,
        ///    &quot;lectureName&quot;: &quot;Information technology&quot;,
        ///    &quot;lectorId&quot;: 2
        ///  },
        ///  {
        ///    &quot;id&quot;: 3,
        ///    &quot;lectureName&quot;: &quot;Psychology&quot;,
        ///    &quot;lectorId&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: 4,
        ///    &quot;lectureName&quot;: &quot;Mathematics&quot;,
        ///    &quot;lectorId&quot;: 3
        ///  },
        ///  {
        ///    &quot;id&quot;: 5,
        ///    &quot;lectureName&quot;: &quot;English&quot;,
        ///    &quot;lectorId&quot;: 4
        ///  },
        ///  {
        ///    &quot;id&quot;: 6,
        ///    &quot;lectureName&quot;: &quot;Cybernetics&quot;,
        ///    &quot;lectorId&quot;: 5
        ///  },
        ///  {
        ///    &quot;id&quot;: 7,
        ///    &quot;lectur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string All_Lectures_json {
            get {
                return ResourceManager.GetString("All_Lectures.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;lectureId&quot;: 2,
        ///    &quot;lectureName&quot;: &quot;Information technology&quot;,
        ///    &quot;studentId&quot;: 2,
        ///    &quot;studentName&quot;: &quot;Grigory Sidorov&quot;,
        ///    &quot;lectureDate&quot;: &quot;2022-03-01T15:31:59.9323118&quot;,
        ///    &quot;grade&quot;: 0,
        ///    &quot;isStudentAttended&quot;: false,
        ///    &quot;lectorName&quot;: &quot;Anatoly Vladimirovich Smolny&quot;
        ///  },
        ///  {
        ///    &quot;lectureId&quot;: 2,
        ///    &quot;lectureName&quot;: &quot;Information technology&quot;,
        ///    &quot;studentId&quot;: 3,
        ///    &quot;studentName&quot;: &quot;Anna Antonova&quot;,
        ///    &quot;lectureDate&quot;: &quot;2022-03-01T15:31:59.9322517&quot;,
        ///    &quot;grade&quot;: 4,
        ///    &quot;isStudentAttended [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string All_LecturesStudents_json {
            get {
                return ResourceManager.GetString("All_LecturesStudents.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 1,
        ///    &quot;name&quot;: &quot;Vasily Petrov&quot;,
        ///    &quot;email&quot;: &quot;v.petrov@gmail.com&quot;,
        ///    &quot;phone&quot;: &quot;+79002318921&quot;,
        ///    &quot;age&quot;: 18
        ///  },
        ///  {
        ///    &quot;id&quot;: 2,
        ///    &quot;name&quot;: &quot;Grigory Sidorov&quot;,
        ///    &quot;email&quot;: &quot;g.sidorov@yandex.ru&quot;,
        ///    &quot;phone&quot;: &quot;+79052010015&quot;,
        ///    &quot;age&quot;: 17
        ///  },
        ///  {
        ///    &quot;id&quot;: 3,
        ///    &quot;name&quot;: &quot;Anna Antonova&quot;,
        ///    &quot;email&quot;: &quot;anna.antonova@yandex.ru&quot;,
        ///    &quot;phone&quot;: &quot;+79103210945&quot;,
        ///    &quot;age&quot;: 18
        ///  },
        ///  {
        ///    &quot;id&quot;: 4,
        ///    &quot;name&quot;: &quot;Svatlana Vasileva&quot;,
        ///    &quot;email&quot;: &quot;s.vasileva@rambler.ru&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string All_Students_json {
            get {
                return ResourceManager.GetString("All_Students.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: 0,
        ///    &quot;subject&quot;: &quot;Homework added from Integration test&quot;,
        ///    &quot;lectureId&quot;: 4
        ///  }.
        /// </summary>
        internal static string New_Homework_json {
            get {
                return ResourceManager.GetString("New_Homework.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: 2,
        ///    &quot;subject&quot;: &quot;Theory of Algorithms&quot;,
        ///    &quot;lectureId&quot;: 2
        ///  }.
        /// </summary>
        internal static string One_Homework_json {
            get {
                return ResourceManager.GetString("One_Homework.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;studentId&quot;: 2,
        ///    &quot;homeworkId&quot;: 1
        ///}.
        /// </summary>
        internal static string One_HomeworkStudent_json {
            get {
                return ResourceManager.GetString("One_HomeworkStudent.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: 3,
        ///    &quot;name&quot;: &quot;Galina Petrovna Antonuk&quot;,
        ///    &quot;email&quot;: &quot;galina.antonuk@universitat.ru&quot;,
        ///    &quot;phone&quot;: &quot;+79019661234&quot;,
        ///    &quot;age&quot;: 43
        ///  }.
        /// </summary>
        internal static string One_Lector_json {
            get {
                return ResourceManager.GetString("One_Lector.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: 2,
        ///    &quot;lectureName&quot;: &quot;Information technology&quot;,
        ///    &quot;lectorId&quot;: 2
        ///  }.
        /// </summary>
        internal static string One_Lecture_json {
            get {
                return ResourceManager.GetString("One_Lecture.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;lectureId&quot;: 2,
        ///    &quot;lectureName&quot;: &quot;Information technology&quot;,
        ///    &quot;studentId&quot;: 3,
        ///    &quot;studentName&quot;: &quot;Anna Antonova&quot;,
        ///    &quot;lectureDate&quot;: &quot;2022-03-01T15:31:59.9322517&quot;,
        ///    &quot;grade&quot;: 4,
        ///    &quot;isStudentAttended&quot;: true,
        ///    &quot;lectorName&quot;: &quot;Anatoly Vladimirovich Smolny&quot;
        ///  }.
        /// </summary>
        internal static string One_LectureStudent_json {
            get {
                return ResourceManager.GetString("One_LectureStudent.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: 3,
        ///    &quot;name&quot;: &quot;Anna Antonova&quot;,
        ///    &quot;email&quot;: &quot;anna.antonova@yandex.ru&quot;,
        ///    &quot;phone&quot;: &quot;+79103210945&quot;,
        ///    &quot;age&quot;: 18
        ///  }.
        /// </summary>
        internal static string One_Student_json {
            get {
                return ResourceManager.GetString("One_Student.json", resourceCulture);
            }
        }
    }
}
